# Exercise 4

## Imports

In [5]:
from enum import Enum
from pathlib import Path

import librosa
from pandas import DataFrame

## Constants

In [6]:
current_dir = Path.cwd()

# Music file
rock_audiofile_path = current_dir.joinpath("data", "rock.mp3")


class Feature(Enum):
    SPECTRAL_CENTROID = "spectral_centroid"
    ZERO_CROSSING_RATE = "zero_crossing_rate"
    ROOT_MEAN_SQUARED_ENERGY = "root_mean_squared_energy"

## Exercise 1

Load the file rock.mp3 from the week 2 exercises in Python and extract the following features with
librosa, once with a frame length of 512 and once with 760:
- Spectral centroid
- Zero-crossing rate
- Root mean squared energy (RMS)

See https://librosa.org/doc/latest/feature.html for documentation on how to extract the features.

In [12]:
def get_column_name(feature: Feature, frame_length: int) -> str:
    return f"{feature.value}-{frame_length}"


# Load audio file
y, sr = librosa.load(rock_audiofile_path)

# Feature dataframe
features_df = DataFrame()

frame_lengths = [512, 760]
for fl in frame_lengths:
    print(f"Extracting features with frame length: {fl}")
    sc = librosa.feature.spectral_centroid(y=y, sr=sr, n_fft=fl)
    features_df[get_column_name(Feature.SPECTRAL_CENTROID, fl)] = sc.flatten()

    zcr = librosa.feature.zero_crossing_rate(y=y, frame_length=fl)
    features_df[get_column_name(Feature.ZERO_CROSSING_RATE, fl)] = zcr.flatten()

    rms = librosa.feature.rms(y=y, frame_length=fl)
    features_df[get_column_name(Feature.ROOT_MEAN_SQUARED_ENERGY, fl)] = rms.flatten()

print(features_df)

Extracting features with frame length: 512
Extracting features with frame length: 760
      spectral_centroid-512  zero_crossing_rate-512  \
0                  0.000000                0.000000   
1                  0.000000                0.000000   
2               6568.019614                0.000000   
3               5023.175337                0.000000   
4               4711.511930                0.210938   
...                     ...                     ...   
9767               0.000000                0.000000   
9768               0.000000                0.000000   
9769               0.000000                0.000000   
9770               0.000000                0.000000   
9771               0.000000                0.000000   

      root_mean_squared_energy-512  spectral_centroid-760  \
0                     0.000000e+00               0.000000   
1                     0.000000e+00            8147.310015   
2                     1.674096e-22            6672.723012   
3        

## Exercise 2

Given the features from Exercise 1, calculate a harmonised feature matrix for all six feature vectors.
The features should be harmonised to the frame length of fmin = 512.
First, use the harmonisation method shown on slide 18 and 19 of the lecture “Feature Processing and
Selection”.
Then, do the same by using a weighted average method in which features of adjacent frames are
weighted by their overlap ratio with the new frame.

## Exercise 3

For each of three feature types, calculate the correlation between the features with frame length 512
from Exercise 1 and the harmonised features with original frame length 760.
Which harmonisation method achieves higher correlation with the extracted features?